namespace EvilHop.Common;

// todo: set to uint value at some point, only done to calculate hashes correctly
public enum AssetType : uint
{
    Animation = 0x414E494D,
    AnimationList,
    AnimationTable,
    BSP,
    Button,
    Camera,
    Counter,
    Conditional,
    Cutscene,
    CutsceneManager,
    CutsceneTable,
    Dispatcher,
    DestructibleObject,
    ElectricArcGenerator,
    Environment,
    Fog,
    Group,
    Gust,
    Hangable,
    Light,
    LobMaster,
    SurfaceMapper,
    ModelInfo,
    Model,
    MorphTarget = 0x4D504854,
    Marker,
    MovePoint,
    NPC,
    ParticleEmitter,
    ParticleSystem,
    Pendulum,
    PickupTable,
    Pickup,
    Platform,
    Player,
    Portal,
    Projectile,
    Texture,
    Script,
    SoundFX,
    SimpleObject,
    Sound,
    SoundInfo,
    StreamingSound,
    Surface,
    Text,
    Timer,
    Trigger,
    UI,
    UIFont,
    Volume
}
